---

name: Action Test

on:
  pull_request:

env:
  PROJECT: ${{ github.repository }}

defaults:
  run:
    shell: bash

jobs:
  action-test:

    name: Run a quick Action test

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        config:
          - name: "action"
            folder: "."

    steps:

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false
          clean: true

      - id: test_action
        name: Test Action
        uses: ./
        with:
          loglevel: "INFO"
          tag_enable: "TRUE"
          tag_force: "FALSE"
          changelog_enable: "TRUE"
          git_pretty_format: "* %h %G? %aN - %s"
          calver_enable: "TRUE"
          calver_scheme: "YYYY.MM.GEN"
          calver_split: "."
          calver_split_mod: "."
          calver_timezone: "Australia/Sydney"

      - id: test_results
        name: Test Results
        run: |
          echo ${{ steps.test_action.outputs.calver }}
